version: 1
formatters:            
    custom:
        format: '%(asctime)s | %(module)-20s | [%(levelname)s]   %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    log_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: custom
        filename: ./logs/logfile.log
        maxBytes: 16777216 # 16MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [log_file_handler]