version: 1
formatters:
  custom:
    format: '%(asctime)s | %(module)-9s | [%(levelname)-9s]  -  %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console_handler:
        class: logging.StreamHandler
        level: DEBUG
        formatter: custom
        stream: ext://sys.stdout

    log_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: custom
        filename: ./data/logs/logfile.log
        maxBytes: 16777216 # 16MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: custom
        filename: ./data/logs/errors.log
        maxBytes: 4194304  # 4MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [console_handler, log_file_handler, error_file_handler]