version: 1
formatters:
    colorful:
        (): colorlog.ColoredFormatter
        fmt: '%(asctime)s | %(module)-10s | [%(tag_log_color)s%(levelname)s%(reset)s]    %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
        secondary_log_colors:
            tag:
                DEBUG: 'blue'
                INFO: 'cyan'
                WARN: 'yellow'
                ERROR: 'red'
                CRIT: 'red'
                
    custom:
        format: '%(asctime)s | %(module)-10s | [%(levelname)s]   %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    console_handler:
        class: logging.StreamHandler
        level: DEBUG
        stream: ext://sys.stdout
        formatter: colorful

    log_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG            
        formatter: custom
        filename: ./data/logs/logfile.log
        maxBytes: 16777216 # 16MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: custom
        filename: ./data/logs/errors.log
        maxBytes: 4194304  # 4MB
        backupCount: 20
        encoding: utf8

root:
    level: DEBUG
    handlers: [console_handler, log_file_handler, error_file_handler]