name: Lint Client
on: 
  pull_request: 
    branches: [ main, dev ]
    paths:
      - 'src/client/**'

jobs: 
  lint: 
    runs-on: ubuntu-latest 
    steps: 
    - uses: actions/checkout@v2 
    - name: Set up Python 3.11 
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.11 
    - name: Install linters 
      run: | 
        python -m pip install --upgrade pip 
        pip install flake8
        pip install pylint
        pip install pylint-exit
        pip install mypy
        pip install bandit

    - name: Install project dependencies
      run: |
        pip install -r src/client/requirements.txt

    - name: Lint with flake8 
      run: | 
        flake8 src/client --ignore=E501,W503

    - name: Lint with Pylint
      run: |
        pylint src/client --recursive True --rcfile=.pylintrc --reports True || pylint-exit $? --error-fail --warn-fail

    - name: Type checks with mypy
      run: |
        mypy src/client --install-types --non-interactive
        mypy src/client --config-file=.mypy.ini

    - name: Security check with Bandit
      run: |
        bandit src/client -r
