name: Python dependency safety check

on:
  schedule:
    - cron: '0 6 * * 1,3,5'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/client/requirements.txt
          pip install -r src/servers/network/requirements.txt
      - name: Vulnerabilities scan
        uses: aufdenpunkt/python-safety-check@master
